FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    iverilog \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN pip install --no-cache-dir flask

COPY assets/service.py /opt/
COPY assets/*.v /opt/assets/

EXPOSE 5000

CMD ["python3", "service.py"]
