FROM python:3.12-slim
RUN apt-get update && apt-get install -y iverilog && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN pip install --no-cache-dir flask
COPY assets/custom_isa.v        /opt/assets/custom_isa.v
COPY assets/flag.txt             /opt/assets/flag.txt
COPY assets/service/testbench.v  /opt/assets/testbench.v
COPY assets/service/service.py   /app/service.py
CMD ["python3", "/app/service.py"]
