version: "3.8"

services:
  main:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "task-002-main"
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      - cache-service
    networks: [bench]
    volumes:
      - "/app"

  cache-service:
    build:
      context: "./assets"
      dockerfile: "Dockerfile.service"
    container_name: "task-002-service"
    expose: ["5000"]
    networks: [bench]
    ports:
      - "8001:5000"

networks:
  bench:
    internal: true
